### ISSUE TITLE
Offering you help

### ISSUE THREAD

**Issue by Domochip** [dotvav/py-palazzetti-api#3]
Hi, 
I'm a developper working on same topic than yours.
I think we can help each other.

The logic around Fumis board is quite complex and there is many subtilities...
That I'm facing right now.

So feel free to ask me any question you encounter.
I have some data and some documentation I gathered during last years.
If you think it's better to do via community, feel free to close this issue and start where you want.

Have a nice evening

**Comment by dotvav** [comment]
Hi, thanks for offering. I have noticed the API is not super straightforward, as I've _worked_ with it for a few years too, and I certainly have a few questions. You can join the [discord server](https://discord.gg/YSKvDNK2) of my Home Assistant integration. This is the main purpose of this library.

**Comment by 5472qaywsx** [comment]
Is the Discord server of this HA integration still active? How can I find it?

**Comment by dotvav** [comment]
Hi, you can find us here https://discord.gg/hzRhWNga

For some reason Discord invitations expire quickly and need to be recreated.
